name: go_do
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.4
  get_storage: any
  intl: any
  google_fonts: any
  awesome_notifications: ^0.8.2
  flutter_local_notifications: 15.1.0+1
  flutter_native_timezone: 2.0.0
  date_picker_timeline: 1.2.5
  sizer: 2.0.15
  sqflite: 2.3.0
  day_night_time_picker: 
  device_preview:
  get: 4.6.5
  flutter: 
    sdk: flutter
  rxdart: ^0.27.7
 

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true


  fonts:
    - family: Cairo 
      fonts:
        - asset: assets/font/Cairo-Black.ttf
          weight: 900
        - asset: assets/font/Cairo-Bold.ttf
          weight: 700
        - asset: assets/font/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Cairo-Light.ttf
          weight: 300
        - asset: assets/font/Cairo-Medium.ttf
          weight: 500
        - asset: assets/font/Cairo-Regular.ttf
          weight: 400
        - asset: assets/font/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/font/Cairo-VariableFont_slnt,wght.ttf
    - family: OpenSans
      fonts:
        - asset: assets/font/OpenSans-Italic-VariableFont_wdth,wght.ttf
        - asset: assets/font/OpenSans-Bold.ttf
        - asset: assets/font/OpenSans-BoldItalic.ttf
        - asset: assets/font/OpenSans-ExtraBold.ttf
        - asset: assets/font/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/font/OpenSans-Italic.ttf
        - asset: assets/font/OpenSans-Italic-VariableFont_wdth,wght.ttf
        - asset: assets/font/OpenSans-Light.ttf
        - asset: assets/font/OpenSans-LightItalic.ttf
        - asset: assets/font/OpenSans-Medium.ttf
        - asset: assets/font/OpenSans-MediumItalic.ttf
        - asset: assets/font/OpenSans-Regular.ttf
        - asset: assets/font/OpenSans-SemiBold.ttf
        - asset: assets/font/OpenSans-SemiBoldItalic.ttf
        - asset: assets/font/OpenSans_Condensed-Bold.ttf
        
        




 

